name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
  - title: '📒 Documentation'
    labels:
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: feature
    title:
      - '/^feat(ure)?[/-].+/'
  - label: bug
    title:
      - '/^fix[/-].+/'
  - label: chore
    branch:
      - '/^chore[/-].+/'
  - label: refactor
    title:
      - '/(refactor|refactoring)[/-].+/'
  - label: documentation
    title:
      - '/doc(umentation)[/-].+/'
    files:
      - '*.md'
  - label: enhancement
    title:
      - '/(enhancement|improve)[/-].+/'
template: |
  ## Changes

  $CHANGES
